spring:
  application:
    name: demo-backend

  # 데이터 베이스
  datasource:
    # 인메모리 모드: jdbc:h2:mem:testdb
    # 파일 모드: jdbc:h2:file:./testdb
#    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:../database/testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
    url: jdbc:mysql://127.0.0.1:3307/demo_mysql
#    url: jdbc:mysql://localhost:3307/demo_mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#  h2:
#    console:
#      enabled: true # H2 Console 사용
#      path: /h2-console # 콘솔 접속 경로 (/h2-console)
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true # SQL 쿼리 로그 출력
#    defer-datasource-initialization: true
